### ISSUE TITLE
BUG: Signup options are not visible 

### ISSUE THREAD

**Issue by Adityajparmar37** [Ayushmaanagarwal1211/casefinal#1]
Description:- signup option is not visible when we scroll down to that section 

Issues video :- 
https://github.com/user-attachments/assets/309bd276-b7a2-47df-8764-02410f80919b

**Comment by Ayushmaanagarwal1211** [comment]
@Adityajparmar37 thanks for raising the issue but actually this is not a Open SOurce Project this is my personal project and i made it public for some reason
